### ISSUE TITLE
Very long error messages when parsing fails

### ISSUE THREAD

**Issue by doriath** [jcornaz/beancount_parser_2#20]
When parser fails, error message contains the whole content of the file starting where the error occurred. When parsing a long beancount ledger, the error message is huge. I would like to suggest trimming the error message (the `fragment` part) to only include the part up to the next new line (or maybe just one or two next linues).

**Comment by jcornaz** [comment]
Hi, thanks for the feedback.

Indeed when formating the error for debug, it was printing the full remaining input. I just changed the behavior it is now fixed in `1.0.0-alpha.7`. Now the error only prints the line number.

This is not the end of the story though, as I plan to improve further the usefulness of error messages: #21.
