### ISSUE TITLE
Custom flags

### ISSUE THREAD

**Issue by doriath** [jcornaz/beancount_parser_2#30]
I am not sure what is the specification of the flag that can be attached to the posting, but I was using `?` and it was parsed by the official parser (but dropped by this one).  This parser only supports `*` and `!`, and just drops all other type of flags.

For now I just replaced `?` with `!` in my ledger, but if we want to be as close to official parser as possible, maybe we should add support for more characters.

**Comment by jcornaz** [comment]
In the language spec the flag must be one of `*` or `!`. `?` is not a valid as far as I understand this page https://github.com/Optravis-LLC/user-management-frontend/compare/682af5dadd4c38ec4f16a19679e6c2bacd8d0844...1472be3e46ff44f26830d416a809b30dbcddb5b6. 

But maybe I am wrong. Maybe a "flag" is any single character? In which case the enum should be replaced by a `char`?

Anyway I am open for suggestions of how that could be supported.

**Comment by jcornaz** [comment]
> but if we want to be as close to official parser as possible, maybe we should add support for more characters.

Note, that's not necessarily the goal. Sure I would like this parser to successfully parse valid beancount syntax as per the language syntax spec. But the exact behavior may differ from the beancount tool.

* I may not support some syntax until its useful for someone
* I may accept some invalid syntax the beancount parser would have rejected

**Comment by jcornaz** [comment]
Actually, it looks like the flag can be any single character. I see [here](https://beancount.github.io/docs/beancount_language_syntax.html#pad) That beancount itself generates transactions with a other flags that `*` or `!`:

```
2014-08-08 P "(Padding inserted for balance of 1137.23 USD)"
  Assets:US:BofA:Checking        149.89 USD
  Equity:Opening-Balances       -149.89 USD
```

So we should trade the `flag` field of posting and the transaction should be of type `char`.

I'm now treating this issue as a bug, because in its current state, the parser could not parse output generated by beancount itself.
