### ISSUE TITLE
Expose list of options

### ISSUE THREAD

**Issue by doriath** [jcornaz/beancount_parser_2#31]
Currently the `BeancountFile,options` is private and it is only possible to check one option at a time using `option` method. What do you think about exposing the list of options (either by exposing the whole HashMap or just the list of keys?

I am happy to contribute, I am just not sure which option is prefered.

**Comment by jcornaz** [comment]
Yes, we can expose a getter to get the list of options. Could be just the keys, or even an iterator of tuples (key, value).

I want to keep the field private though. As a matter of fact, I plan to make most fields of most structs private as part of the stabilization process.

Just out of curiosity may I ask what's your use case?

**Comment by doriath** [comment]
I am trying to do "read-modify-write" scripts for beancount - for example rename the accounts, perform stock split, categorize transactions. For that, I am planning to use this parser to parse my beancount file, then convert parser data structure into my own (which currently are almost the same as this crate, just using owned String instead of &str), perform modifications and then output beancount file again.

For now I just have reading the file and the immediately writing it back, to see if all data is properly parsed (which is where all my recent PRs / issues are coming from). I pushed the code to https://github.com/doriath/beancount-exp.

If you plan to make the fields private, how will it be possible to extract the data (do you plan to write getters for all fields)?

**Comment by jcornaz** [comment]
Thanks for sharing your use-case. Sounds cool :-)

> If you plan to make the fields private, how will it be possible to extract the data (do you plan to write getters for all fields)?

Yes, all data will be available through getters. But the getters may hide some type information. For example `Transaction::postings` result type will be something like `&[Posting]` or `impl Iterator<Item=&Posting>`, but certainly not `Vec<Posting>` so that I retain the ability to change the actual underlying type.

**Comment by jcornaz** [comment]
This is solved in main. I'll release it later today.

I just want to make an update about my approach for public fields. I think I'll not make *all* fields private, some will stay public. 

Fields will be private depending on their type:

* If the type is a collection type `Vec`, `HashSet` or `HashMap` the field will be made private, and opaque-iterators will be provided, potentially alongside some other utility methods (so that I can change to a different collection type later)
* If the type is `Copy` (`Account` and `Currency` ), the field will be private too, and there will be a getter returning ownership, so that I may change the internal representation in the future.
* Other fields will probably stay public so that the users can mutate them and/or acquire ownership without me having to create 3/4 different getters/setters for each field.

Note, this is not set in stone (yet). I may still change my mind until 1.0.0.
